print("Welcome to the band Name Generator.")
print("What's name of the city you grew up  in?")
namel=input()
print("What's your pet's name?")
pet=input()
print("Your band name could be " + namel +" "+pet)
